name: Execute Tests

on:
  push:
    branches: [ mega ]
  pull_request:
    branches: [ mega ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import os
            os.system('python3 test.py')
